# area of the environment
area:
 x_min: -100
 x_max: 100
 y_min: -5
 y_max: 100

#all static and dynamic obstacles 
obstacles:
 - # wall right
  centroid_x: 70
  centroid_y: 23
  dx: 10
  dy: 40
  orientation: 30
  velocity_x: 0
  velocity_y: 0
  acc_x: 0
  acc_y: 0

 - # parked right
  centroid_x: 45
  centroid_y: 17
  dx: 3
  dy: 5
  orientation: -90
  velocity_x: 0
  velocity_y: 0
  acc_x: 0
  acc_y: 0

 - # wall left
  centroid_x: -65
  centroid_y: 20
  dx: 15
  dy: 500
  orientation: 0 
  velocity_x: 0
  velocity_y: 0
  acc_x: 0
  acc_y: 0

 - # parked left
  centroid_x: -40
  centroid_y: 10
  dx: 2
  dy: 5
  orientation: -60
  velocity_x: 0
  velocity_y: 0
  acc_x: 0
  acc_y: 0

 - # parked left up
  centroid_x: -40
  centroid_y: 25
  dx: 2
  dy: 5
  orientation: -60
  velocity_x: 0
  velocity_y: 0
  acc_x: 0
  acc_y: 0

 - # move down
  centroid_x: 25
  centroid_y: 80
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: -0.7
  velocity_y: 0
  acc_x: 0
  acc_y: 0

 - # vehicle move up acceleration
  centroid_x: -25
  centroid_y: -70
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.5
  acc_x: 0
  acc_y: 0.1

 - # vehicle move up no acceleration
  centroid_x: -25
  centroid_y: 65
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.8
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: 58
  dx: 3
  dy: 6
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: 50
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: 40
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: 35
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: 26
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: 10
  dx: 3.5
  dy: 7
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: 2
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: -13
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -28
  centroid_y: 3
  dx: 4
  dy: 0
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move down no acceleration
  centroid_x: 25
  centroid_y: 130
  dx: 4
  dy: 7
  orientation: 0
  velocity_x: -1
  velocity_y: 0
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: -40
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: -50
  dx: 3.5
  dy: 7
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: -65
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: -82
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move up no acceleration behind
  centroid_x: -25
  centroid_y: -100
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: 0.7
  acc_x: 0
  acc_y: 0

 - # vehicle move down no acceleration
  centroid_x: -25
  centroid_y: 160
  dx: 3
  dy: 4
  orientation: 0
  velocity_x: 0
  velocity_y: -1.1
  acc_x: 0
  acc_y: 0